# Generated by Django 4.0 on 2023-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_wtachagain_review_watchagain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=2500),
        ),
    ]
